// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_4NHEL8C5vMdVZRV9UeZ4-o9jLukasEk',
    appId: '1:487617827074:web:477bd970632cb3deb5f21b',
    messagingSenderId: '487617827074',
    projectId: 'groceryapp-8ce26',
    authDomain: 'groceryapp-8ce26.firebaseapp.com',
    storageBucket: 'groceryapp-8ce26.firebasestorage.app',
    measurementId: 'G-ECNTBZGS8W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS_LKV5CfhlEyKS3QihZZ1yX3gH0WS204',
    appId: '1:487617827074:android:a26694b919724c52b5f21b',
    messagingSenderId: '487617827074',
    projectId: 'groceryapp-8ce26',
    storageBucket: 'groceryapp-8ce26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsS6tZcIKeLuEhh4ng-1opJUy-VVqepC0',
    appId: '1:487617827074:ios:d589dd0b7863f717b5f21b',
    messagingSenderId: '487617827074',
    projectId: 'groceryapp-8ce26',
    storageBucket: 'groceryapp-8ce26.firebasestorage.app',
    iosBundleId: 'com.example.groceryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsS6tZcIKeLuEhh4ng-1opJUy-VVqepC0',
    appId: '1:487617827074:ios:d589dd0b7863f717b5f21b',
    messagingSenderId: '487617827074',
    projectId: 'groceryapp-8ce26',
    storageBucket: 'groceryapp-8ce26.firebasestorage.app',
    iosBundleId: 'com.example.groceryapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_4NHEL8C5vMdVZRV9UeZ4-o9jLukasEk',
    appId: '1:487617827074:web:ae1df5528a41c3efb5f21b',
    messagingSenderId: '487617827074',
    projectId: 'groceryapp-8ce26',
    authDomain: 'groceryapp-8ce26.firebaseapp.com',
    storageBucket: 'groceryapp-8ce26.firebasestorage.app',
    measurementId: 'G-5C09SJQQ4E',
  );
}
